const stockProductos = [
  {
    id: 1,
    nombre: "Acondicionador de Keratina",
    cantidad: 1,
    desc: "Acondicionador FIDELITE Keratina X 240ml.",
    precio: 595,
    img: "../imagenes/img/conditioner-keratin_2.jpg",
  },
  {
    id: 2,
    nombre: "Protector termico Yilho",
    cantidad: 1,
    desc: "Protector Termico X 125cc. con gatillo",
    precio: 1156,
    img: "../imagenes/img/protector yilho.png",
  },
  {
    id: 3,
    nombre: "Guantes de nitrilo",
    cantidad: 1,
    desc: "Guantes de Nitrilo negro x Par",
    precio: 50,
    img: "../imagenes/img/guantenitrilo.jpeg",
  },
  {
    id: 4,
    nombre: "Crema de peinar Mav",
    cantidad: 1,
    desc: "Crema de peinar MAV Macadamia y Caviar para todo tipo de cabello X 250ml.",
    precio: 986,
    img: "../imagenes/img/crema mav.png",
  },
  {
    id: 5,
    nombre: "Ionizado reestructurante nov",
    cantidad: 1,
    desc: "Ionizado Nov X 3 ampollas",
    precio: 663,
    img: "../imagenes/img/ionizado.jpeg",
  },
  {
    id: 6,
    nombre: "Crema de peinar multi",
    cantidad: 1,
    desc: "Crema de peinar caviar FIDELITE para todo tipo de cabellos X 250ml.",
    precio: 765,
    img: "../imagenes/img/crema-de-peinado-multiaccion.png",
  },
  {
    id: 7,
    nombre: "Crema de peinar argan",
    cantidad: 1,
    desc: "Crema de Peinar Caviar FIDELITE de Argan X 250ml.",
    precio: 833,
    img: "../imagenes/img/cremapeinarargan.jpeg",
  },
  {
    id: 8,
    nombre: "serum reparador bekim",
    cantidad: 1,
    desc: "Serum Bekim Argan X 30ml.",
    precio: 1411,
    img: "../imagenes/img/serumbekim.jpeg",
  },
  {
    id: 9,
    nombre: "Crema peinar rbx",
    cantidad: 1,
    desc: "Crema de Peinar RBX para todo tipo de cabellos x 300ml.",
    precio: 544,
    img: "../imagenes/img/cremapeinarrbx.jpeg",
  },
];